### ISSUE TITLE
NULLs appear in emails

### ISSUE THREAD

**Issue by hjylewis** [danielmichaelni/journey#4]

**Comment by charlesetc** [comment]
Does this happen every time?

**Comment by hjylewis** [comment]
Not every time, not even for every location field in the same email.  I can forward you examples.

**Comment by charlesetc** [comment]
I mean, does it ever remove the (null) and just say the city and state?

**Comment by hjylewis** [comment]
I get Cupertino CA.  Maybe you are only replacing the null of the first two fields but not all.  When all four fields are null, we get (null) (null).

Could that be it?

**Comment by charlesetc** [comment]
That's exactly it. I'll fix it now.

**Comment by charlesetc** [comment]
Done—it now says "the location" when they're no location read.
